# Copyright (C) 2020 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Android CI

on:
  push:
    branches: [ gha ]
  pull_request:
    branches: [ gha ]

jobs:
    test_job:
      name: Test
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'

        - name: Restore Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Run Debug Tests
          run: ./gradlew testDebugUnitTest --continue

        - name: Upload Test Reports
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: test-reports
            path: '**/build/reports/tests/'

    code_formatting_job:
      name: Code Formatting
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Run Debug ktlint
          run: ./gradlew ktlintDebugCheck --continue

        - name: Upload ktlint Reports
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: ktlint-report
            path: '**/build/reports/ktlint'

    lint_job:
      name: Lint
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: Restore Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Run Debug Lint
          run: ./gradlew lintDebug

        - name: Upload Lint Reports
          if: ${{ always() }}
          uses: actions/upload-artifact@v2
          with:
            name: lint-report
            path: '**/build/reports/lint-results-*'

    assemble_job:
      name: Assemble
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:

        - name: Checkout
          uses: actions/checkout@v2

        - name: Restore Cache
          uses: actions/cache@v2
          with:
            path: |
              ~/.gradle/caches
              ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
            restore-keys: |
              ${{ runner.os }}-gradle-

        - name: Assemble Debug
          run: ./gradlew assembleDebug

        - name: Upload APK
          uses: actions/upload-artifact@v2
          with:
            name: apk
            path: app/build/outputs/apk/debug/**.apk